---
# This workflow runs whenever there is a push to the dev branch.
# It performs lint, tests, and build to ensure dev stays stable.

name: "Dev CI"

on:
  push:
    branches: [ "dev" ]

jobs:

  test:
    name: "Lint, type check, test and build"
    uses: ./.github/workflows/shared/test.yml
    with:
      run-coverage: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
